const ADD_POST = "ADD_POST";
const DELETE_POST = "DELETE_POST";
const EDIT_POST = "EDIT_POST";

const GET_POST = "GET_POST";
const GET_ALL_TITLES = "GET_TITLES";

const ADD_COMMENT = "ADD_COMMENT";
const DELETE_COMMENT = "DELETE_COMMENT";

const VOTE_TITLE = "VOTE_TITLE";
const VOTE_POST = "VOTE_POST";
export {
  ADD_POST,
  DELETE_POST,
  EDIT_POST,
  ADD_COMMENT,
  DELETE_COMMENT,
  GET_ALL_TITLES,
  GET_POST,
  VOTE_POST,
  VOTE_TITLE
};
